version: "3.8"

services:

  zipkin:
    image: openzipkin/zipkin
    mem_limit: 2048m
    ports:
      - "9411:9411"
    networks:
     - bank
  eureka:
    image: 241174/slueth-zipkin-eureka:latest
    mem_limit: 2048m
    ports:
      - "8761:8761"
    networks:
     - bank 
    depends_on:
      - zipkin 
    environment:
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/ 
      - "SPRINGPROFILES=actuator"      
  account:
    image: 241174/slueth-zipkin-account:latest
    mem_limit: 2048m
    ports:
      - "8080:8080"
    networks:
     - bank
    depends_on:
       - eureka
       - card
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s    
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
  loans:
    image: 241174/slueth-zipkin-loans:latest
    mem_limit: 2048m
    ports:
      - "8082:8082"
    networks:
     - bank
    depends_on:
       - eureka
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s    
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
  card:
    image: 241174/slueth-zipkin-card:latest
    mem_limit: 2048m
    ports:
      - "8081:8081"
    networks:
     - bank
    depends_on:
       - eureka
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s    
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
    
  gateway:
    image: 241174/slueth-zipkin-gateway:latest
    mem_limit: 2048m
    ports:
      - "8074:8074"
    networks:
     - bank
    depends_on:
      - eureka
      - card
      - loans
      - account
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s    
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
networks:
    bank:     
    